OrdererOrgs:
  - Name: Orderer
    Domain: fl-ddos.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Client1
    Domain: client1.fl-ddos.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Client2
    Domain: client2.fl-ddos.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Client3
    Domain: client3.fl-ddos.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
